### ISSUE TITLE
syntax error near unexpected token `>'

### ISSUE THREAD

**Issue by sebastiansutter** [ibm-apiconnect/v2018-postmortem#1]
I ran the script:
./generate_postmortem.sh --diagnostic-gateway
Generating postmortem, please wait...
./generate_postmortem.sh: line 258: syntax error near unexpected token `>'
./generate_postmortem.sh: line 258: `                    kubectl exec busybox -- nslookup $endpoint &>>"${APICUP_ENDPOINT_DATA}/nslookup-${name}.out"'
Cleaning up.  Removing directory [/tmp/postmortem-20190415T125221CEST].

I think the & sign is not intended in line 258. Removing that allowed me to run

**Comment by nitekon1** [comment]
@sebastiansutter My apologies, just now noticed this issue.
What OS are you running the script on?  I am not able to recreate on CentOS / RHEL 6.x / 7.x, Fedora 30, Ubuntu 16.04 and 18.04.

**Comment by sebastiansutter** [comment]
@nitekon1 I ran the script on MacOS 10.13

**Comment by nitekon1** [comment]
@sebastiansutter Awesome will test on my Mac soon and get back you with.  Thanks!

**Comment by nitekon1** [comment]
Fixed in latest version.
