### ISSUE TITLE
Seeing err when executing `./generate_postmortem.sh --ova`

### ISSUE THREAD

**Issue by yiting0219** [ibm-apiconnect/v2018-postmortem#12]
Getting error when running the script on APIC OVA installed appliance with the command `./generate_postmortem.sh --ova`
```
root@apimdev1190:~# ./generate_postmortem.sh --ova
Generating postmortem, please wait...
INFO[0000] Log level: info
Error from server (NotFound): pods "NAME" not found
Error from server (NotFound): pods "default" not found
Error from server (NotFound): pods "kube-node-lease" not found
Error from server (NotFound): pods "kube-public" not found
Error from server (NotFound): pods "kube-system" not found
Created [/tmp/apiconnect-logs-apimdev1190-20191118T205825UTC.zip].
Cleaning up.  Removing directory [/tmp/postmortem-20191118T205825UTC].
```
After troubleshooting, look like the bug is in line https://github.com/ibm-apiconnect/v2018-postmortem/blob/master/generate_postmortem.sh#L375
which has a missing `-n` when filtering namespace.

Open ticket request for the fix.

**Comment by nitekon1** [comment]
Fixed in commit f7989d9ff1b10ebabbb1f3a1745e40c54eb55e7a
