### ISSUE TITLE
 Collect apic cluster custom resource info on ICP4I platform

### ISSUE THREAD

**Issue by mkolinsk** [ibm-apiconnect/v2018-postmortem#16]
`kubectl get apiconnectclusters -o yaml -n <installation namespace>`
Note that that this is the operator's equivalent to the apiconnect-up.yml file used by apicup

**Comment by nitekon1** [comment]
How does one determine the `installation namespace`?

**Comment by nitekon1** [comment]
Fixed in commit 7cc52af4b997a4011d0a1e01213b61e360ea5784.
