### ISSUE TITLE
Add new --extra-namespaces="apic1 apic2" parameter to input namespaces.

### ISSUE THREAD

**Issue by subindani** [ibm-apiconnect/v2018-postmortem#17]
This is required for usecases where 
- helm is not installed and we need to get logs from the apic namespace in cloud pak for integration.
- if there are any additional namespaces that we could loop through and get the logs.

**Comment by nitekon1** [comment]
Fixed in commit 7cc52af4b997a4011d0a1e01213b61e360ea5784.
