### ISSUE TITLE
Collect system logs from ova

### ISSUE THREAD

**Issue by curtisr7** [ibm-apiconnect/v2018-postmortem#18]
The current post mortem script only gathers the syslogs from the node running the script. This doesn't help when running in a multi-node setup. One quick and dirty solution would be to collect the output from `apic logs`.... though that would duplicate some of the logs currently collected by post mortem.

**Comment by nitekon1** [comment]
Setting up an environment to recreate this behavior.

**Comment by nitekon1** [comment]
Added switch `--pull-appliance-logs` in commit 8edac4245d1739de793a6f6a1441f915eca0123b.
