### ISSUE TITLE
Script stuck in line 692

### ISSUE THREAD

**Issue by sebastiansutter** [ibm-apiconnect/v2018-postmortem#2]
After removing the & as described in issue #1, the script is executing, but finally gets stuck in line 692.
$ ./generate_postmortem.sh --diagnostic-gateway
Generating postmortem, please wait...
./generate_postmortem.sh: line 237: ${line1,,}: bad substitution
./generate_postmortem.sh: line 312: ${namespace,,}: bad substitution
./generate_postmortem.sh: line 692: conditional binary operator expected
./generate_postmortem.sh: line 692: syntax error near `"$REPORT_PATH"'
./generate_postmortem.sh: line 692: `                    if [[ ! -v "$REPORT_PATH" ]]; then'
Cleaning up.  Removing directory [/tmp/postmortem-20190415T125409CEST].
[debug.log](https://github.com/ibm-apiconnect/v2018-postmortem/files/3079832/debug.log)

**Comment by nitekon1** [comment]
Fixed in latest version.
