### ISSUE TITLE
Log gathering is incomplete on OVA if tiller pod is not responding

### ISSUE THREAD

**Issue by xor76** [ibm-apiconnect/v2018-postmortem#21]
If `helm ls` returns the following error
Error: could not find a ready tiller pod
the log collection will not be performed for the `default` namespace on OVA, to get around this delete the tiller pod from `kube-system`

Can we have the script returning the error from helm and the possible solution if that is the case?

**Comment by nitekon1** [comment]
In commit 8edac4245d1739de793a6f6a1441f915eca0123b, added code to detect empty helm deployments and offer to restart tiller pod.
