### ISSUE TITLE
Add description about switch --log-limit  to the documentation.

### ISSUE THREAD

**Issue by kajagana** [ibm-apiconnect/v2018-postmortem#22]
v2018 generate post mortem tool at the time of generation known to use large amount of disk space.  To limit the size, the tool can be run with a switch  --log-limit=<value> in the form
     generate_postmortem.sh  --diagnostic-analytics --log-limit=20000

Please document the use of switch here.

**Comment by subindani** [comment]
Yes, this is planned for the next refresh of the readme. @nitekon1 FYI

**Comment by nitekon1** [comment]
Added documentation update to script in commit 8edac4245d1739de793a6f6a1441f915eca0123b.
