### ISSUE TITLE
generate_postmortem.sh fails to collect pod logs when APIC is deployed in default namespace

### ISSUE THREAD

**Issue by subindani** [ibm-apiconnect/v2018-postmortem#28]
+ User deployed APIC 2018 in default namespace

+ Running :
```
./generate_postmortem.sh --diagnostic-portal --diagnostic-manager --no-apicup --extra-namespaces=default 
```
does not collect pod logs.

+ Collected debug using:
```
./generate_postmortem.sh --diagnostic-portal --diagnostic-manager --no-apicup --extra-namespaces=<namespace where apic is deployed> --log-limit=2  --debug &>debug.log
```

+ It seems there is some issue with the script since I see in debug :
```
NAMESPACE_LIST=kube-system
```

It did not take the "default" value passed with --extra-namespaces parameter.

+ Maybe its an issue with the switch statement at Line 12.

+ Regardless, as a workaround, we updated this variable to :
NAMESPACE_LIST=kube-system default
at  Line 212 in https://raw.githubusercontent.com/ibm-apiconnect/v2018-postmortem/master/generate_postmortem.sh
just before the condition to check if NAMESPACE_LIST exists at 

``` 
NAMESPACE_LIST=kube-system default

if [[ -z "$NAMESPACE_LIST" ]]; then
    NAMESPACE_LIST="kube-system"
fi
```

**Comment by nitekon1** [comment]
Just pushed out a code change, let me know if this fixed the issue.

**Comment by nitekon1** [comment]
@subindani ^

**Comment by subindani** [comment]
Thank you @nitekon1
