### ISSUE TITLE
Missing ssh Argument in ova Deployment

### ISSUE THREAD

**Issue by danchirillo** [ibm-apiconnect/v2018-postmortem#3]
Step #1 in the ova deployment instructions is incomplete.  In order to ssh to the device, the apicadm user ID **must** be passed.  If it isn't, a permission denied( public key) error will be returned.  The instruction should be:
ssh apicadm@{ova appliance hostname} **-l apicadm**

**Comment by nitekon1** [comment]
While the command:
```ssh apicadm@{hostname}```
is not incorrect, some distributions may have issues with this syntax.  Updated to ```ssh {hostname} -l apicadm`

**Comment by danchirillo** [comment]
I take this issue back.  When reading the instructions, my eyes **completely** missed **apicadm@**; I read the ssh command it as **ssh {ova appliance hostname}**, which is why I indicated in the issue description that the apicadm user ID needs to be passed.
