### ISSUE TITLE
Enhancement to add option to disable auto-detection of namespaces

### ISSUE THREAD

**Issue by mkolinsk** [ibm-apiconnect/v2018-postmortem#33]
Add ability to disable auto-detection of namespaces and only collect data from kube-system and the namespaces listed in the `--extra-namespaces` switch

**Comment by mkolinsk** [comment]
Can this be addressed with the same fix for this v10 issue? 
https://github.com/ibm-apiconnect/v10-postmortem/issues/4

**Comment by nitekon1** [comment]
Added in commit 9b9b8cb78a30e6ca672081a72ec5fefd7ba2db8f.
