### ISSUE TITLE
Postmortem is not collection default namespace in 2018.4.1.15 OVA

### ISSUE THREAD

**Issue by xor76** [ibm-apiconnect/v2018-postmortem#35]
Problem is due to the line:
https://github.com/ibm-apiconnect/v2018-postmortem/blob/8ef0489e1b4d69fbd8b5a685be8827a2da6bec23/generate_postmortem.sh#L401

which does not return the namespace in fp15.

**Comment by nitekon1** [comment]
Fixed in commit 9b9b8cb78a30e6ca672081a72ec5fefd7ba2db8f.
