### ISSUE TITLE
Syntax Error Running Script

### ISSUE THREAD

**Issue by danchirillo** [ibm-apiconnect/v2018-postmortem#4]
Environment:  2018.4.1.4 ova management subsystem

**Behavior**
root@chirillo-apim:~# ./generate_postmortem.sh --ova
Generating postmortem, please wait...
./generate_postmortem.sh: line 254: syntax error near unexpected token `&'
./generate_postmortem.sh: line 254: `                    kubectl exec busybox -- nslookup $endpoint >>"${APICUP_ENDPOINT_DATA}/nslookup-${name}.out" 2>>&1'
Cleaning up.  Removing directory [/tmp/postmortem-20190614T155119UTC].

**Comment by nitekon1** [comment]
Fixed line of code.
