### ISSUE TITLE
Need to change the default log limit size from 10000 to something much higher

### ISSUE THREAD

**Issue by mkolinsk** [ibm-apiconnect/v2018-postmortem#6]
For the vast In the vast majority of issues we will need the log limit to be set considerably higher. We should set the default to 0 and let clients change from default if collecting all the lines of each pod is taking too much time or causing the compressed file to be too large.  At a minimum, the default should be increased by a magnitude of 100x.

**Comment by nitekon1** [comment]
Fixed in commit c3a527c.
