### ISSUE TITLE
Collect analytics related diagnostics 

### ISSUE THREAD

**Issue by xor76** [ibm-apiconnect/v2018-postmortem#8]
In order to better understand the status of the analytics cluster it would help to have the output of the following commands

kubectl exec -n $NAMESPACE $storage-pod -- curl_es "_cluster/health?pretty"
kubectl exec -n $NAMESPACE $storage-pod -- curl_es "_cat/nodes?v"
kubectl exec -n $NAMESPACE $storage-pod -- curl_es "_cat/indices?v"
kubectl exec -n $NAMESPACE $storage-pod -- curl_es "_cat/shards?v"
kubectl exec -n $NAMESPACE $storage-pod -- curl_es "curl_es _alias?pretty"
kubectl exec -n $NAMESPACE $storage-pod -- curl_es "_cluster/allocation/explain?pretty"

kubectl exec -n $NAMESPACE $ingestion pod -- curl "localhost:9600/_node/stats?pretty"

**Comment by nitekon1** [comment]
Added in commit 7f179fa.
